SELECT CURRENT_USER();
SELECT CURRENT_ROLE();
SELECT CURRENT_WAREHOUSE();
SELECT CURRENT_DATABASE();
SELECT CURRENT_SCHEMA();


CREATE OR REPLACE DATABASE UNIVERSITY_DB;

USE DATABASE UNIVERSITY_DB;

CREATE OR REPLACE SCHEMA ACADEMIC_SCHEMA;

USE SCHEMA ACADEMIC_SCHEMA;

CREATE OR REPLACE WAREHOUSE CAMPUS_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE CAMPUS_WH;


CREATE OR REPLACE TABLE LEARNERS (
    LEARNER_ID INT,
    LEARNER_NAME STRING,
    STREAM STRING,
    SCORE INT
);

CREATE OR REPLACE STAGE DATA_STAGE;


SHOW DATABASES;
SHOW SCHEMAS;
SHOW WAREHOUSES;
SHOW TABLES;
SHOW STAGES;


INSERT INTO LEARNERS VALUES
(201, 'Aarav', 'CSE', 82),
(202, 'Priya', 'ECE', 91),
(203, 'Kunal', 'IT', 76);

SELECT * FROM LEARNERS;


UPDATE LEARNERS
SET SCORE = 94
WHERE LEARNER_ID = 202;

SELECT * FROM LEARNERS;


DELETE FROM LEARNERS
WHERE LEARNER_ID = 203;

SELECT * FROM LEARNERS;


CREATE OR REPLACE TABLE EXAM_PERFORMANCE (
    GENDER STRING,
    RACE_ETHNICITY STRING,
    PARENTAL_LEVEL_OF_EDUCATION STRING,
    LUNCH STRING,
    TEST_PREPARATION_COURSE STRING,
    MATH_SCORE INT,
    READING_SCORE INT,
    WRITING_SCORE INT
);

LIST @DATA_STAGE;


CREATE OR REPLACE FILE FORMAT EXAM_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


COPY INTO EXAM_PERFORMANCE
FROM @DATA_STAGE/StudentsPerformance.csv
FILE_FORMAT = EXAM_CSV_FORMAT;

SELECT COUNT(*) AS TOTAL_RECORDS
FROM EXAM_PERFORMANCE;

SELECT *
FROM EXAM_PERFORMANCE
LIMIT 10;


CREATE OR REPLACE TABLE STAFF (
    STAFF_ID INT,
    STAFF_NAME STRING,
    SALARY INT
);

INSERT INTO STAFF VALUES
(1, 'Arjun', 52000),
(2, 'Meera', 61000),
(3, 'Vivek', 57000);

SELECT * FROM STAFF;


UPDATE STAFF
SET SALARY = 72000
WHERE STAFF_ID = 1;

DELETE FROM STAFF
WHERE STAFF_ID = 3;

SELECT * FROM STAFF;


SELECT *
FROM STAFF
AT(OFFSET => -60);


INSERT INTO STAFF
SELECT *
FROM STAFF
AT(OFFSET => -60)
WHERE STAFF_ID = 3;

SELECT * FROM STAFF;
